name 'ericsson-sudo'
version '0.3.0'
source 'git://github.com/Ericsson/puppet-module-sudo.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'manage sudo'
description 'manage sudo with ability to not manage package or sudoers file'
project_page 'https://github.com/Ericsson/puppet-module-sudo'

dependency 'puppetlabs/stdlib', '3.2.x'
